Updated README example
LeastAuthority/txkube pull request #39
Opened 2017-01-28 01:57 UTC by exarkun

Fixes #35 

Note I haven't actually run this code.  It _probably_ works. :wink: I'll try it in the next few days and update the issue with results.

2017-01-30 12:50 UTC, wallrj requested changes
I didn't read your PR comment so my first instinct was to try running this from my laptop, resulting in this error:

```
richard@drax:~/.../LeastAuthority/txkube (35.readme-example)$ KUBERNETES_SERVICE_HOST=127.0.0.1 KUBERNETES_SERVICE_PORT=41973 python example.py 
Traceback (most recent call last):
  File "example.py", line 9, in <module>
    @react
  File "/home/richard/.virtualenvs/txkube/lib/python2.7/site-packages/twisted/internet/task.py", line 908, in react
    finished = main(_reactor, *argv)
  File "example.py", line 11, in main
    agent = authenticate_with_serviceaccount(reactor)
  File "/home/richard/projects/LeastAuthority/txkube/src/txkube/_authentication.py", line 224, in authenticate_with_serviceaccount
    config = KubeConfig.from_service_account(**kw)
  File "/home/richard/.virtualenvs/txkube/lib/python2.7/site-packages/pykube/config.py", line 22, in from_service_account
    with open(os.path.join(path, "token")) as fp:
IOError: [Errno 2] No such file or directory: '/var/run/secrets/kubernetes.io/serviceaccount/token'

```

Then when I read your PR comment it looks like you're running this example from a POD that you've started in minikube.
But the Docker image `exarkun/txkube:6` must be something you've created locally.

It's a cool example, and a realistic example of the typical use of txkube, but I think you'll need to provide a further details about how this example demonstrates how you might use txkube from *inside* the Kubernetes cluster.

And have a previous example showing how to use txkube from outside the kubernetes cluster....using code similar to the integration test setup.

The integration test instructions work and the tests all passed with my minikube cluster.

2017-01-30 13:50 UTC, exarkun commented
Legit.  I went with an in-pod example because the setup for outside-cluster is somewhat more verbose.  If you think the fact that the in-pod example is not a good introduction, I can wait on updating the readme until it's easier to do outside-cluster auth.  I thought this might still be a worthwhile change because the readme in master is entirely wrong.

2017-01-31 20:46 UTC, exarkun commented
@wallrj I think this should be much nicer now.  What do you think?

2017-02-01 11:03 UTC, exarkun commented
I think this is reasonable now and I want fewer open PRs.

2017-02-01 11:04 UTC, merged