Fix unresolved name issue
LeastAuthority/txkube pull request #8
Opened 2017-01-20 23:42 UTC by adamtheturtle

This was found with `pyflakes`. I'd be happy to add a `pyflakes` checker to the Travis config if that is desired.

2017-01-20 23:43 UTC, adamtheturtle commented on src/txkube/testing/_eliot.py
> +from eliot import add_destination, remove_destination
See https://github.com/LeastAuthority/txkube/pull/8/files#diff-58b820f05af5c1f18e36eef9bede77cbR64 for the use of this.

2017-01-21 01:32 UTC, exarkun commented
> I'd be happy to add a pyflakes checker to the Travis config if that is desired.

@adamtheturtle Yea, that'd be awesome.  It's on my todo list but happy for someone else to get there first.  Feel free to stick some of those other static checks you mentioned elsewhere in, if they seem appropriate.

2017-01-21 01:34 UTC, exarkun requested changes

2017-01-21 01:34 UTC, exarkun commented on src/txkube/testing/_eliot.py
> +from eliot import add_destination, remove_destination
Yep.  This is only half the fix, as it turns out.  I noticed the problem at some point during development of #5 - there is actually no `Fixture._tearDown`  :(  Instead, the code should `self.addCleanup(...)` inside `_setUp`.  Feel like doing the rest of that here?

2017-01-23 13:52 UTC, merged

2017-01-23 13:53 UTC, adamtheturtle commented
Yes I'll get to the other 😄